---
title: "This is all test code. DISCLAIMER: MAY NOT BE CLEEAAN"
author: "Dalton"
date: "1/14/2020"
output: html_document
---

The code below is for Dalton's testing. If you can't read it, I do not care. It is meant for me. If I think it is useful, it will be cleaned and added to RegressionTesting.Rmd

-Kthxbye

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl) 
Keybrdg_LS_Removed_Redundant_Rows <- read.csv("/cloud/project/Data/Keybrdg_LS_Removed_Redundant_Rows.csv", header=FALSE)
Q1 <- read_excel("Data/LegalShieldQ1.xlsx", sheet = 1, skip = 0)
```


```{r baf}
summary(Keybrdg_LS_Removed_Redundant_Rows)
summary(Q1)

```

```{r}
n = nrow(Keybrdg_LS_Removed_Redundant_Rows["V3"])
table(Keybrdg_LS_Removed_Redundant_Rows['V3'])
cbind(table(Keybrdg_LS_Removed_Redundant_Rows['V3'])/n)
```

```{r Pivot Table (State x Product)}
library(pivottabler)
pt <- PivotTable$new()
pt$addData(Keybrdg_LS_Removed_Redundant_Rows)
pt$addColumnDataGroups("V3")
pt$addRowDataGroups("V2")
pt$defineCalculation(calculationName="Claims by State", summariseExpression="n()")
pt$renderPivot() 
```
```{r Linear Model}
lmTotalSpendSales =  lm(Q1$totally~Q1$TotalX)
lmLglSpendSales = lm(Q1$Legal...5~Q1$`Total LGL`)
lmBusSpendSales = lm(Q1$BUS...13~Q1$`Total BUS`)
lmLchSpendSales = lm(Q1$Launch...17~Q1$`Total LCH`)
lmEspSpendSales = lm(Q1$`LS En Espanol...21`~Q1$`Total Legal Espanol`)
lmIdsSpendSales = lm(Q1$SAIDT~Q1$`Total IDS`)
lmMultiVariateSpendSales = lm(Q1$totally~Q1$`Total LGL` + Q1$`Total BUS` + Q1$`Total IDS` + Q1$`Total LCH` + Q1$`Total Legal Espanol` + Q1$TotalX)
plot(lmTotalSpendSales, pch = 16, col = "red")
summary(lmTotalSpendSales)
summary(lmLglSpendSales)
summary(lmBusSpendSales)
summary(lmLchSpendSales)
summary(lmEspSpendSales)
summary(lmIdsSpendSales)
summary(lmMultiVariateSpendSales)

```

```{r}
plot(lmTotalSpendSales)
abline(lmSpendSales, col="blue") #Create the linear regression
```

```{r modeling data}
set.seed(100)
## creates an index for randomly sampling observations for data partitioning
index = sample(1:nrow(Q1), 0.7 * nrow(Q1))

## train containing 70% of the data and test containing 30% of the data
train = Q1[index, ] # Create the training data
test = Q1[-index, ] # Create the test data

dim(train)
dim(test)

## Regularization

## cols are meant to select only factors we are interested in from the train/test data
cols = c("Total LGL", "Total BUS", "Total IDS", "Total LCH")

##centers and scales data for training models
pre_proc_val <-
  preProcess(train[, cols], method = c("center", "scale"))

train[, cols] = predict(pre_proc_val, train[, cols])
test[, cols] = predict(pre_proc_val, test[, cols])

summary(train)
lr = lm(
  train$TotalX ~  train$`Total LGL` + train$`Total BUS` + train$`Total IDS` + train$`Total LCH` + train$`Total Legal Espanol`
)
summary(lr)

cols_reg = c("Total LGL",
             "Total BUS",
             "Total IDS",
             "Total LCH",
             "Total Legal Espanol",
             "TotalX")

dummies <- dummyVars(TotalX ~ ., data = Q1[, cols_reg])

train_dummies = predict(dummies, newdata = train[, cols_reg])

test_dummies = predict(dummies, newdata = test[, cols_reg])

print(dim(train_dummies))
print(dim(test_dummies))

library(glmnet)
##create the training data matrices for the independent (x) and dependent variables (y).
x = as.matrix(train_dummies)
y_train = as.matrix(train$TotalX)

x_test = as.matrix(test_dummies)
y_test = as.matrix(test$TotalX)
lambdas <- 10 ^ seq(2,-3, by = -.1)
```
```{r Actual Regression}
##ridge_reg = glmnet(x, y_train, nlambda = 25, alpha = 0, family = 'gaussian', lambda = lambdas)
##print(dummies)
##summary(ridge_reg)
```

``` {r}
lambdas <- 10^seq(2, -3, by = -.1)

# Setting alpha = 1 implements lasso regression
##lasso_reg <- cv.glmnet(x, y_train, alpha = 1, lambda = lambdas, standardize = TRUE, nfolds = 5)

# Best 
##lambda_best <- lasso_reg$lambda.min 
##lambda_best
##ridge_reg = glmnet(x, y_train, nlambda = 25, alpha = 0, family = 'gaussian', lambda = lambdas)

##summary(ridge_reg)
```

```{r plots}
plot(lr)

plot(train$`Total LGL` + train$`Total BUS` + train$`Total IDS` + train$`Total LCH` + train$`Total Legal Espanol`,train$TotalX )

plot(train$`Total LGL` + train$`Total BUS` + train$`Total IDS` + train$`Total LCH` + train$`Total Legal Espanol`, train$TotalX ,
main="Spend Vs. Sales",
ylab="",
type="l",
col="blue")
legend("topleft",
c("Total Legal","Total BUS","Total IDS","Total LCH"),
fill=c("blue","red","black","yellow")
)
```
